export const countries = [
  {
    id: "abcd100",
    name: "United States",
    capital: "Washington",
    flagImage: "🇺🇸",
    population: 331893745,
    region: "Americas",
  },
  {
    id: "abcd101",
    name: "Germany",
    capital: "Berlin",
    flagImage: "🇩🇪",
    population: 83166711,
    region: "Europe",
  },
  {
    id: "abcd102",
    name: "India",
    capital: "New Delhi",
    flagImage: "🇮🇳",
    population: 1380004385,
    region: "Asia",
  },
  {
    id: "abcd103",
    name: "Canada",
    capital: "Ottawa",
    flagImage: "🇨🇦",
    population: 37742154,
    region: "Americas",
  },
  {
    id: "abcd104",
    name: "Brazil",
    flagImage: "🇧🇷",
    capital: "Brasilia",
    population: 212559417,
    region: "Americas",
  },
  {
    id: "abcd105",
    name: "United Kingdom",
    capital: "London",
    flagImage: "🇬🇧",
    population: 67886011,
    region: "Europe",
  },
  {
    id: "abcd106",
    name: "Australia",
    capital: "Canberra",
    flagImage: "🇦🇺",
    population: 25687041,
    region: "Oceania",
  },
  {
    id: "abcd107",
    name: "China",
    capital: "Beijing",
    flagImage: "🇨🇳",
    population: 1395788604,
    region: "Asia",
  },
  {
    id: "abcd108",
    name: "France",
    capital: "Paris",
    flagImage: "🇫🇷",
    population: 65273511,
    region: "Europe",
  },
  {
    id: "abcd109",
    name: "Russia",
    capital: "Moscow",
    flagImage: "🇷🇺",
    population: 145912025,
    region: "Europe",
  },
  {
    id: "abcd110",
    name: "Japan",
    flagImage: "🇯🇵",
    capital: "Tokyo",
    population: 126851743,
    region: "Asia",
  },
  {
    id: "abcd111",
    name: "South Africa",
    capital: "Pretoria",
    flagImage: "🇿🇦",
    population: 59308690,
    region: "Africa",
  },
  {
    id: "abcd112",
    name: "Mexico",
    capital: "Ciudad de México",
    flagImage: "🇲🇽",
    population: 128933800,
    region: "Americas",
  },
  {
    id: "abcd113",
    name: "Italy",
    capital: "Rome",
    flagImage: "🇮🇹",
    population: 60244639,
    region: "Europe",
  },
  {
    id: "abcd114",
    name: "Spain",
    capital: "Madrid",
    flagImage: "🇪🇸",
    population: 46719142,
    region: "Europe",
  },
  {
    id: "abcd115",
    name: "Argentina",
    capital: "Buenos Aires",
    flagImage: "🇦🇷",
    population: 45195777,
    region: "Americas",
  },
  {
    id: "abcd116",
    name: "Egypt",
    capital: "Cairo",
    flagImage: "🇪🇬",
    population: 91250000,
    region: "Africa",
  },
  {
    id: "abcd117",
    name: "Saudi Arabia",
    capital: "Riyadh",
    flagImage: "🇸🇦",
    population: 34813871,
    region: "Asia",
  },
  {
    id: "abcd118",
    name: "Indonesia",
    capital: "Jakarta",
    flagImage: "🇮🇩",
    population: 273523615,
    region: "Asia",
  },
  {
    id: "abcd119",
    name: "Pakistan",
    capital: "Islamabad",
    flagImage: "🇵🇰",
    population: 220892340,
    region: "Asia",
  },
  {
    id: "abcd120",
    name: "Turkey",
    capital: "Ankara",
    flagImage: "🇹🇷",
    population: 84339067,
    region: "Europe",
  },
  {
    id: "abcd121",
    name: "Bangladesh",
    capital: "Dhaka",
    flagImage: "🇧🇩",
    population: 164689383,
    region: "Asia",
  },
  {
    id: "abcd122",
    name: "Nigeria",
    capital: "Abuja",
    flagImage: "🇳🇬",
    population: 206139589,
    region: "Africa",
  },
  {
    id: "abcd123",
    name: "South Korea",
    capital: "Seoul",
    flagImage: "🇰🇷",
    population: 51329899,
    region: "Asia",
  },
  {
    id: "abcd124",
    name: "Colombia",
    capital: "Bogotá",
    flagImage: "🇨🇴",
    population: 50882891,
    region: "Americas",
  },
  {
    id: "abcd125",
    name: "Kenya",
    capital: "Nairobi",
    flagImage: "🇰🇪",
    population: 53771296,
    region: "Africa",
  },

  {
    id: "abcd126",
    name: "Ukraine",
    capital: "Kyiv",
    flagImage: "🇺🇦",
    population: 43733762,
    region: "Europe",
  },
  {
    id: "abcd127",
    name: "Poland",
    capital: "Warsaw",
    flagImage: "🇵🇱",
    population: 38386000,
    region: "Europe",
  },
  {
    id: "abcd128",
    capital: "Baghdad",
    name: "Iraq",
    flagImage: "🇮🇶",
    population: 40222493,
    region: "Asia",
  },
  {
    id: "abcd129",
    name: "Afghanistan",
    flagImage: "🇦🇫",
    region: "Asia",
  },
  {
    id: "abcd130",
    name: "Venezuela",
    capital: "Caracas",
    flagImage: "🇻🇪",
    population: 28435943,
    region: "Americas",
  },
  {
    id: "abcd131",
    name: "Sudan",
    capital: "Juba",
    flagImage: "🇸🇸",
    population: 43849260,
    region: "Africa",
  },
  {
    id: "abcd132",
    name: "Morocco",
    capital: "Rabat",
    flagImage: "🇲🇦",
    population: 36910560,
    region: "Africa",
  },
  {
    id: "abcd133",
    name: "Uzbekistan",
    capital: "Tashkent",
    flagImage: "🇺🇿",
    population: 33469203,
    region: "Asia",
  },
  {
    id: "abcd134",
    name: "Malaysia",
    capital: "Kuala Lumpur",
    flagImage: "🇲🇾",
    population: 32365999,
    region: "Asia",
  },
  {
    id: "abcd135",
    name: "Nepal",
    capital: "Kathmandu",
    flagImage: "🇳🇵",
    population: 29136808,
    region: "Asia",
  },
  {
    id: "abcd136",
    name: "Sri Lanka",
    capital: "Colombo",
    flagImage: "🇱🇰",
    population: 21413249,
    region: "Asia",
  },
  {
    id: "abcd137",
    name: "Chile",
    capital: "Santiago",
    flagImage: "🇨🇱",
    population: 18952038,
    region: "Americas",
  },
  {
    id: "abcd138",
    name: "Guatemala",
    capital: "Guatemala City",
    flagImage: "🇬🇹",
    population: 17915568,
    region: "Americas",
  },
  {
    id: "abcd139",
    name: "Czech Republic",
    capital: "Prague",
    flagImage: "🇨🇿",
    population: 10649800,
    region: "Europe",
  },
  {
    id: "abcd140",
    name: "Belgium",
    capital: "Brussels",
    flagImage: "🇧🇪",
    population: 11589623,
    region: "Europe",
  },
  {
    id: "abcd141",
    name: "Hungary",
    capital: "Budapest",
    flagImage: "🇭🇺",
    population: 9660351,
    region: "Europe",
  },
  {
    id: "abcd142",
    name: "Tunisia",
    capital: "Tunis",
    flagImage: "🇹🇳",
    population: 11818619,
    region: "Africa",
  },
  {
    id: "abcd143",
    name: "Lithuania",
    capital: "Vilnius",
    flagImage: "🇱🇹",
    population: 2722289,
    region: "Europe",
  },
  {
    id: "abcd144",
    name: "Luxembourg",
    capital: "Luxembourg",
    flagImage: "🇱🇺",
    population: 634814,
    region: "Europe",
  },
  {
    id: "abcd145",
    name: "Bulgaria",
    capital: "Sofia",
    flagImage: "🇧🇬",
    population: 6948445,
    region: "Europe",
  },

  {
    id: "abcd146",
    name: "Qatar",
    capital: "Doha",
    flagImage: "🇶🇦",
    population: 2881053,
    region: "Asia",
  },
  {
    id: "abcd147",
    name: "Mauritius",
    capital: "Port Louis",
    flagImage: "🇲🇺",
    population: 1271768,
    region: "Africa",
  },
  {
    id: "abcd148",
    name: "Algeria",
    capital: "Algiers",
    flagImage: "🇩🇿",
    population: 43851044,
    region: "Africa",
  },
  {
    id: "abcd149",
    name: "Romania",
    capital: "Bucharest",
    flagImage: "🇷🇴",
    population: 19237691,
    region: "Europe",
  },
  {
    id: "abcd150",
    name: "Croatia",
    capital: "Zagreb",
    flagImage: "🇭🇷",
    population: 4105267,
    region: "Europe",
  },
  {
    id: "abcd151",
    name: "New Zealand",
    capital: "Wellington",
    flagImage: "🇳🇿",
    population: 4822233,
    region: "Oceania",
  },
  {
    id: "abcd152",
    name: "Iceland",
    capital: "Reykjavik",
    flagImage: "🇮🇸",
    population: 343599,
    region: "Europe",
  },
  {
    id: "abcd153",
    name: "Finland",
    capital: "Helsinki",
    flagImage: "🇫🇮",
    population: 5540720,
    region: "Europe",
  },
  {
    id: "abcd154",
    name: "Norway",
    capital: "Oslo",
    flagImage: "🇳🇴",
    population: 5421241,
    region: "Europe",
  },
  {
    id: "abcd155",
    name: "Sweden",
    capital: "Stockholm",
    flagImage: "🇸🇪",
    population: 10353442,
    region: "Europe",
  },
  {
    id: "abcd156",
    name: "Denmark",
    capital: "Copenhagen",
    flagImage: "🇩🇰",
    population: 5792202,
    region: "Europe",
  },
  {
    id: "abcd157",
    name: "Slovakia",
    capital: "Bratislava",
    flagImage: "🇸🇰",
    population: 5456362,
    region: "Europe",
  },
  {
    id: "abcd158",
    name: "Slovenia",
    capital: "Ljubljana",
    flagImage: "🇸🇮",
    population: 2078654,
    region: "Europe",
  },
  {
    id: "abcd159",
    name: "Latvia",
    capital: "Riga",
    flagImage: "🇱🇻",
    population: 1886198,
    region: "Europe",
  },
  {
    id: "abcd160",
    name: "Estonia",
    capital: "Tallinn",
    flagImage: "🇪🇪",
    population: 1326535,
    region: "Europe",
  },
  {
    id: "abcd161",
    name: "Malta",
    capital: "Valletta",
    flagImage: "🇲🇹",
    population: 514064,
    region: "Europe",
  },
  {
    id: "abcd162",
    name: "Cyprus",
    capital: "Nicosia",
    flagImage: "🇨🇾",
    population: 1207361,
    region: "Europe",
  },
  {
    id: "abcd163",
    name: "Armenia",
    capital: "Yerevan",
    flagImage: "🇦🇲",
    population: 2963243,
    region: "Asia",
  },
  {
    id: "abcd164",
    name: "Georgia",
    capital: "Tbilisi",
    flagImage: "🇬🇪",
    population: 3989167,
    region: "Asia",
  },
  {
    id: "abcd165",
    name: "Moldova",
    capital: "Chisinau",
    flagImage: "🇲🇩",
    population: 2657637,
    region: "Europe",
  },
  {
    id: "abcd166",
    name: "Belarus",
    capital: "Minsk",
    flagImage: "🇧🇾",
    population: 9449323,
    region: "Europe",
  },
  {
    id: "abcd167",
    name: "Serbia",
    capital: "Belgrade",
    flagImage: "🇷🇸",
    population: 8772235,
    region: "Europe",
  },
  {
    id: "abcd168",
    name: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    flagImage: "🇧🇦",
    population: 3280819,
    region: "Europe",
  },
  {
    id: "abcd169",
    name: "Montenegro",
    capital: "Podgorica",
    flagImage: "🇲🇪",
    population: 622359,
    region: "Europe",
  },
  {
    id: "abcd170",
    name: "Kosovo",
    capital: "Pristina",
    flagImage: "🇽🇰",
    population: 1831000,
    region: "Europe",
  },
  {
    id: "abcd171",
    name: "North Macedonia",
    capital: "Skopje",
    flagImage: "🇲🇰",
    population: 2083459,
    region: "Europe",
  },
  {
    id: "abcd172",
    name: "Albania",
    capital: "Tirana",
    flagImage: "🇦🇱",
    population: 2877797,
    region: "Europe",
  },
  {
    id: "abcd173",
    name: "Andorra",
    capital: "Andorra la Vella",
    flagImage: "🇦🇩",
    population: 77265,
    region: "Europe",
  },
  {
    id: "abcd174",
    name: "Liechtenstein",
    capital: "Vaduz",
    flagImage: "🇱🇮",
    population: 38128,
    region: "Europe",
  },
  {
    id: "abcd175",
    name: "San Marino",
    capital: "San Marino",
    flagImage: "🇸🇲",
    population: 33931,
    region: "Europe",
  },
  {
    id: "abcd176",
    name: "Monaco",
    capital: "Monaco",
    flagImage: "🇲🇨",
    population: 39242,
    region: "Europe",
  },
  {
    id: "abcd177",
    name: "Vatican City",
    capital: "Vatican City",
    flagImage: "🇻🇦",
    population: 800,
    region: "Europe",
  },
  {
    id: "abcd178",
    name: "Macau",
    capital: "Macao",
    flagImage: "🇲🇴",
    population: 649342,
    region: "Asia",
  },
  {
    id: "abcd179",
    name: "Hong Kong",
    capital: "Hong Kong",
    flagImage: "🇭🇰",
    population: 7496981,
    region: "Asia",
  },
  {
    id: "abcd180",
    name: "Taiwan",
    capital: "Taipei",
    flagImage: "🇹🇼",
    population: 23816775,
    region: "Asia",
  },
  {
    id: "abcd181",
    name: "Singapore",
    capital: "Singapur",
    flagImage: "🇸🇬",
    population: 5850342,
    region: "Asia",
  },
  {
    id: "abcd182",
    name: "Brunei",
    capital: "Bandar Seri Begawan",
    flagImage: "🇧🇳",
    population: 437483,
    region: "Asia",
  },
  {
    id: "abcd183",
    name: "Kuwait",
    capital: "Kuwait City",
    flagImage: "🇰🇼",
    population: 4270563,
    region: "Asia",
  },
  {
    id: "abcd184",
    name: "Oman",
    capital: "Muscat",
    flagImage: "🇴🇲",
    population: 5106626,
    region: "Asia",
  },
  {
    id: "abcd185",
    name: "Yemen",
    capital: "Sanaa",
    flagImage: "🇾🇪",
    population: 29825964,
    region: "Asia",
  },
  {
    id: "abcd186",
    name: "Jordan",
    capital: "Amman",
    flagImage: "🇯🇴",
    population: 10203134,
    region: "Asia",
  },
  {
    id: "abcd187",
    name: "Lebanon",
    capital: "Beirut",
    flagImage: "🇱🇧",
    population: 6825445,
    region: "Asia",
  },
  {
    id: "abcd188",
    name: "Syria",
    capital: "Damascus",
    flagImage: "🇸🇾",
    population: 17500658,
    region: "Asia",
  },
];
